FROM pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime
RUN apt-get update &&\
apt-get -y install tmux&&\
apt-get -y install python3.8&&\
apt-get -y install python3-pip&&\
apt-get -y install nano&&\
apt-get -y install git&&\
pip install --upgrade pip&&\
pip install --no-cache-dir ipywidgets==8.0.2 numpy==1.23.4 datasets==2.7.0 transformers==4.24.0 pandas==1.5.1 flask==2.2.2 cherche==1.0.1 scikit-learn==1.1.3 sentence-transformers==2.2.2 tqdm==4.62.3 jupyterlab==3.5.0 traitlets>=5.2.2 ipython>=7.23.1 typing-extensions>=4.1.0
